var fs = require('fs');
var package = require('./package.json');

var pkgInfo = `
/**
 * DO NOT manually change this file.
 * This file is automatically generated by npm scripts.
 */
export const pkgInfo = {
    version: '${package.version}',
    envName: '${process.argv[2]}'
}`;

fs.writeFileSync('src/environments/package-info.ts', pkgInfo, 'utf-8');
